### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by HappyPantss** [ofahchouch-gh/cahoot-back-end#1]
Hey Oussama,

Ik zal hier opschrijven wat je nog mist van de peer review steps!

* Je hebt nog geen link naar de live demo bovenin/ in je repo.
* 🚨 Je .env staat nog in je repo, en die zou ik zo snel mogelijk in je .gitignore zetten!!! Want hier staat gevoelige informatie in 🚨
* Je hebt iets over je concept, data life cycle en real-time events?.. daarnaast nog geen beschrijving over je installation en external api info.

*  Zoals eerder gezegd, er staat nog niet wat je external api voor data geeft.
* Er staat nog geen key van de api die gebruikt kan worden om te connecten

~ Voor de rest ziet het er top uit, keep coding!

**Comment by ofahchouch-gh** [comment]
Thanks voor de feedback :)! 

Ik ga btw niet met een externe API werken, maar een eigen uitgebreide database maken. Het is niet verplicht om met een externe API te werken namelijk. Voor een kahoot clone heb ik geen API nodig, ik maak mijn eigen uitgebreide back-end en database.

**Comment by HappyPantss** [comment]
Aha ook gaaf! En ja klopt, misschien kan je hier ook wat over schrijven ipv iets over een API. Succes!
