### ISSUE TITLE
Repository feedback

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/cahoot-back-end#2]
Hi,

Great that you already personalized most of the repository! Makes it easy to see what it is about in a gander.
But I don't see a live link yet.. It will probably be added soon in the future! I will look forward to it!

I see that you have a .env, for the future (or after deleting it) create a `.env.template` to show developers how the .env file should look like!

Great that the readme looks complete! I will read it in a moment!

**Comment by dewarian** [comment]
The [README](https://github.com/ofahchouch-gh/cahoot-back-end/blob/main/README.md) is structured in a clear manner and has a TOC! That's great. It contains everything specified in the peer-review and is comparable with the rubric.

**Comment by ofahchouch-gh** [comment]
Thanks, zal je feedback verwerken over .env
