### ISSUE TITLE
Feedback week 2

### ISSUE THREAD

**Issue by johancvb** [ofahchouch-gh/cahoot-back-end#3]
## Repo

Je repo is super gedetailleerd en uitgebreid, bevat alleen geen live link, maar heeft een duidelijke opbouw. Het concept van de app wordt goed uitgelegd, en ondersteund met sketches van je webapp. Je data-model, class-diagram, en data lifecycle ondersteunen je webapp heel goed, en maken je webapp een stuk makkelijker te begrijpen. Het enige wat nog mist aan je ReadMe is de installatie.

## Code

Ik zie dat je nog een .env bestand mee pushed, en dit wordt afgeraden in het feedback-template. (https://github.com/cmda-minor-web/real-time-web-2021/blob/main/course/peer-review.md)

Voor de rest zie ik dat je voor bijna elke functie een eigen file maakt. Dit maakt het super overzichtelijk, alleen soms misschien een beetje onnodig als een functie misschien heel klein is. Verder is je code wel gewoon strak, goed opgedeeld, met veel consistentie opgebouwd, en overall gewoon vlekkeloos. Hier kan ik (als code-noob) niet echt veel aan opmerken 😉
Blijf zo doorgaan, dat weet ik dat er een super vette app uitkomt.

--Johan

**Comment by ofahchouch-gh** [comment]
Thanks, zal je feedback verwerken!
