### ISSUE TITLE
Concept feedback

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/cahoot-back-end#4]
Hi,

The concept is clear for someone who knows Kahoot, but what If I don't know Kahoot? It might be unclear what it might be!

**Comment by dewarian** [comment]
The structure of the code looks good and concise, as usual it is clear that you have a solid background in Object Oriented Programming.

I see in [backend/sockets/CahootSocket.js](https://github.com/ofahchouch-gh/cahoot-back-end/blob/main/sockets/CahootSocket.js) that you have some static questions. Is the idea that this is for testing purposed until you have created the admin section before you connect the socket questions to the database?

**Comment by dewarian** [comment]
About the data model I don't have anything to say, it is clear and concise, the models for mongoose are a direct copy and the relations look good?

The reason I mention it in a questionable manner is because of the way it is written, could you elaborate why the data model relations are written like
`1 <has 2..3` or `1 <has 1`?

**Comment by ofahchouch-gh** [comment]
Ja de CahootSocket heeft static data, omdat ik nog aan het testen ben :). Die data moet straks uit de database komen.

Dat zijn de relaties, one to many, many to many, many to one, of 1 tot 2..3 bijvoorbeeld. Dit hadden we geleerd tijdens onze opleiding Informatica. Wat het nut er van is weet ik eigenlijk niet, het is meer handig, voor nu dan. Misschien dat het pas nuttig is in grotere projecten.
