### ISSUE TITLE
Data lifecycle & Sockets feedback

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/cahoot-back-end#5]
Hi Again,

Nice that you individually mentions every socket event and what it should do or will be doing!

## Data lifecycle

Good that you described the lifecycle in human linguistics instead of developer linguistics! It makes it easier to understand what happens!.

I do see a typo at ['...deze op middels de persistenc.' ](https://github.com/ofahchouch-gh/cahoot-back-end#data-lifecycle) might be a quicky, but is nice to know!.

The only real remark I could give you about the data lifecycle is that the text is kind of small in the elements. You might want to bump the font-size up a tiny bit.

**Comment by ofahchouch-gh** [comment]
Thanks, aangepast :)!
