### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by johancvb** [ofahchouch-gh/cahoot-back-end#6]
Je ReadMe ziet er heel goed uit, zoals vorige week ook al vermeld, en is heel gedetailleerd. Alleen is het misschien een leuk idee om Emoji's in de headers te gebruiken. Dit geeft een leuker thema aan je ReadMe, en maakt het ook overzichtelijker.

**Comment by ofahchouch-gh** [comment]
Thanks voor de tip, zal dat doen als ik tijd over heb :)!
