### ISSUE TITLE
Backend Repository Readme

### ISSUE THREAD

**Issue by dewarian** [ofahchouch-gh/cahoot-back-end#8]
Hi,

**Disclaimer: Ik zal alleen de repo van je backend beoordelen, aangezien we hierop worden beoordeeld.**

Mooi dat je de informatie beknopt heb gehouden van je applicatie. 
Wel mis ik nog een link naar de cahoot, maar zoals beschreven in issue #2 zal je dat waarschijnlijk nog verwerken.

Duidelijk dat je laat zien welke features er wel of niet zijn geimplementeerd.

Tip voor de socket events, wellicht is het duidelijker om het te weergeven in een tabel ipv een bullet list.
(Zie example in de comments.)

**Comment by dewarian** [comment]
Voorbeeld van hoe je de events duidelijk in structuur kan brengen.

|TypeOf|Event|Action|
|:-|:--|--|
|on|`getNextQuestion`| Clients ontvangen nieuwe vraag |
|emit|`getnextQuestion`| Admin emit een event waarbij de nieuwe vraag wordt verdeeld aan de clients. |
|typeOf|event|desciption|

**Comment by dewarian** [comment]
Verder heb ik geen opmerkingen te plaatsen want dat was de vorige keer al goed beschreven. (e.g. lifecycle, datamodel etc.)

**Comment by dewarian** [comment]
Feedback tijdens de review met wouter:
Voor de room functionaliteit:
 ```this.io.to(PIN).emit('EVENTNAME', functionality);```
 Voor rooms documentatie: https://socket.io/docs/v4/rooms/index.html
 
[Voor deploy zou je eventueel beide repo's in dezelfde Dyno. (indien je de front-end in dezelfde repo plaats in een source folder)](https://www.freecodecamp.org/news/deploying-a-mern-application-using-mongodb-atlas-to-heroku/#deploying-to-heroku). Hoop dat je hier iets aan hebt, maar denk dat je het niet nodig hebt aangezien je het op je eigen server wilt hosten.
 
 Bij invullen van de vragen worden de placeholders verwijderd waardoor je niet meer weet wat je invult, dus dit is wellicht prettiger met Labels
 
Radio button verduidelijken, dat je weet dat de radiobutton de juiste vraag is.

Data lifecycle op dit moment erg abstract, maar mis nog welke events worden gestuurd. met eventuele data model dat voor dat event is.

**Comment by ofahchouch-gh** [comment]
Thanks voor de feedback, appreciate it!
